# CMake generated Testfile for 
# Source directory: /home/n71743ev/DUMUX/dumux/Aquifer/appl/Cartesian/Test2
# Build directory: /home/n71743ev/DUMUX/dumux/Aquifer/build-cmake/appl/Cartesian/Test2
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(appl_2pncgeobio_biogeochemical_tpfa2_cart "/home/n71743ev/DUMUX/dumux/Aquifer/build-cmake/appl/Cartesian/Test2/appl_2pncgeobio_biogeochemical_tpfa2_cart" "params.input")
set_tests_properties(appl_2pncgeobio_biogeochemical_tpfa2_cart PROPERTIES  LABELS "" PROCESSORS "1" REQUIRED_FILES "/home/n71743ev/DUMUX/dumux/Aquifer/build-cmake/appl/Cartesian/Test2/appl_2pncgeobio_biogeochemical_tpfa2_cart" SKIP_RETURN_CODE "77" TIMEOUT "300" WORKING_DIRECTORY "/home/n71743ev/DUMUX/dumux/Aquifer/build-cmake/appl/Cartesian/Test2" _BACKTRACE_TRIPLES "/home/n71743ev/DUMUX/dumux/dune-common/cmake/modules/DuneTestMacros.cmake;417;add_test;/home/n71743ev/DUMUX/dumux/dumux/cmake/modules/DumuxTestMacros.cmake;210;dune_add_test;/home/n71743ev/DUMUX/dumux/Aquifer/appl/Cartesian/Test2/CMakeLists.txt;5;dumux_add_test;/home/n71743ev/DUMUX/dumux/Aquifer/appl/Cartesian/Test2/CMakeLists.txt;0;")
add_test(appl_2pncgeobio_biogeochemical_box2_cart "/home/n71743ev/DUMUX/dumux/Aquifer/build-cmake/appl/Cartesian/Test2/appl_2pncgeobio_biogeochemical_box2_cart" "params.input")
set_tests_properties(appl_2pncgeobio_biogeochemical_box2_cart PROPERTIES  LABELS "" PROCESSORS "1" REQUIRED_FILES "/home/n71743ev/DUMUX/dumux/Aquifer/build-cmake/appl/Cartesian/Test2/appl_2pncgeobio_biogeochemical_box2_cart" SKIP_RETURN_CODE "77" TIMEOUT "300" WORKING_DIRECTORY "/home/n71743ev/DUMUX/dumux/Aquifer/build-cmake/appl/Cartesian/Test2" _BACKTRACE_TRIPLES "/home/n71743ev/DUMUX/dumux/dune-common/cmake/modules/DuneTestMacros.cmake;417;add_test;/home/n71743ev/DUMUX/dumux/dumux/cmake/modules/DumuxTestMacros.cmake;210;dune_add_test;/home/n71743ev/DUMUX/dumux/Aquifer/appl/Cartesian/Test2/CMakeLists.txt;17;dumux_add_test;/home/n71743ev/DUMUX/dumux/Aquifer/appl/Cartesian/Test2/CMakeLists.txt;0;")
